### ISSUE TITLE
 Datasource vmware vmware-rpctool Permission denied

### ISSUE THREAD

**Issue by playerla** [canonical/cloud-init#4436]
Hi,

Following a security configuration https://github.com/vmware/open-vm-tools/issues/690 (metadata, vendordata or userdata are all readable by any local user with the defautl configuration...) 
I learn that :
> rpctool does not support secure RPCs, and we'd like to deprecate it.
> 'vmtoolsd --cmd' does support secure RPCs, and is the preferred way to execute RPCs.

I'm know stuck with a datasource vmware vmware-rpctool _Permission denied_ :
https://github.com/canonical/cloud-init/blob/97e09dfea2d74ef583bd5650b5c6e40aa19fbb24/cloudinit/sources/DataSourceVMware.py#L92

In what extend rpctool could be replaced with vmtoolsd  ? (optional switch, impact or even deprecation?)

**Comment by TheRealFalcon** [comment]
@playerla , do you have documentation for how `vmtoolsd` is supposed to be used? If it is meant to be a replacement for rpctools, then it makes sense to update in the VMWare datasource.

cc: @sshedi and @akutz

**Comment by akutz** [comment]
This was raised internally as well. The tl;dr:

### Context

* The tool `vmware-rpctool` is failing due to a secure RPC feature implemented in ESXi that currently is only supported by `vmtoolsd`.
* Why did we switch from `vmtoolsd` to `vmware-rpctool` in the first place? For that please see https://github.com/vmware-archive/cloud-init-vmware-guestinfo/pull/23
  * `vmtoolsd` was subject to a performance issue that was patched on the ESXi side an in open-vm-tools
  * It is not possible for the guest to know whether the hypervisor is running with that patch

### Short-term solution

* @ravindravmw recommended that if `vmware-rpctool` fail, we fall back to `vmtoolsd`
* My concern was that returning no data is a perfectly valid scenario, so failing has to be based on a specific condition, not just a non-zero exit code
* We decided to fall back to `vmtoolsd` if `vmware-rpctool` returns a non-zero exit code and writes `Permission denied` to `stderr`. 

### Long-term plan

* In the long-run, we want to move back to `vmtoolsd` anyway as it supports other features new in vSphere 8.0, such as datasets, a more robust data transport model than guestinfo. 
* However, again, Cloud-Init and the guest won't know what the host supports, so we need to develop a migration/fall-back strategy for `vmware-rpctool` --> `vmtoolsd` that:
  * Does not cause performance issues on older hosts
  * Allows the use of secure RPC and datasets on new hosts

### Action Items

- [ ] @ravindravmw Can the secure RPC feature can be added to `vmware-rpctool` so it is no longer subject to `permission denied` errors.
- [ ] ravindravmw Can `vmware-rpctool` be updated to support datasets?

**Comment by TheRealFalcon** [comment]
Thanks @akutz , that helps a lot. Given this, I agree that a fallback to `vmtoolsd` makes the most sense currently.

**Comment by akutz** [comment]
> Thanks @akutz , that helps a lot. Given this, I agree that a fallback to `vmtoolsd` makes the most sense currently.

Agreed. And I would have honestly submitted a PR by now, but have not for the same reason I have not added support for datasets. If it was just in the DS, that would be one thing, but ds_identify has to be updated as well. I've been wracking my brain to try and figure out a way to unify the two approaches...

**Comment by TheRealFalcon** [comment]
Yeah, I have noticed the VMWare section of ds-identify is a little more complicated than some other datasources. Is there nothing else within the environment to identify an instance as being on VMWare/vSphere?

**Comment by akutz** [comment]
Perhaps, but I should also address the OvfEnv DS as well, which this affects since it also uses `vmware-rpctool`. I'm working on it now. I'll put something up sans tests for folks to review, and then work on, or get someone to help work on, the tests for it.

**Comment by akutz** [comment]
> Yeah, I have noticed the VMWare section of ds-identify is a little more complicated than some other datasources. Is there nothing else within the environment to identify an instance as being on VMWare/vSphere?

@TheRealFalcon I remember the other reason it is complicated. As I am looking at the tests for `ds_identify`, validating the VMware logic required distinct functions for each property to mock, hence all the funcs.

**Comment by cpaelzer** [comment]
> Yeah, I have noticed the VMWare section of ds-identify is a little more complicated than some other datasources. Is there nothing else within the environment to identify an instance as being on VMWare/vSphere?

If it is, as usual, just about identifying "on vmware" then it is about ["Mechanisms to determine if software is running in a VMware virtual machine"](https://kb.vmware.com/s/article/1009458) which e.g. [systemd-detect-virt](https://www.freedesktop.org/software/systemd/man/systemd-detect-virt.html) already [uses](https://github.com/systemd/systemd/blob/main/src/basic/virt.c#L84).

But that will only tell you where you are, not give you any config data. Furthermore you already have that as `detect_virt` uses this and `vmware_guest_customization` is first checking `[ "${DI_VIRT}" = "vmware" ]`.

Only later in `dscheck_VMware` comes all the complexity as there are various combinations how it could be configured and therefore of fetching that data on that platform.

**Comment by playerla** [comment]
Thank you for you reactivity ! I just get the daily build but still _Permission denied._ 
I can't figure why. Open up #4475
