### ISSUE TITLE
ImportError: No distribution found for distro suse

### ISSUE THREAD

**Issue by smoshiur1237** [canonical/cloud-init#4525]
# Bug report
I was trying to install cloud-init from source github repo in SUSE Enterprise 15 SP4. I am getting the ImprotError and also some warnings which eventually failed the process.

## Steps to reproduce the problem
The following command were used to install cloud-init:
```
git clone https://github.com/canonical/cloud-init.git
cd cloud-init
sudo python3 -m pip install -r requirements.txt
sudo python3 setup.py build
sudo python3 setup.py install --init-system systemd
sudo cloud-init init --local   # Failure occurs on this step
sudo cloud-init status
```
We can see the ImportError of suse during `init --local `stage. There was no `suse` distro module in the source code(sles, opensuse and other opensuse, sles option is available) and I think that is the issue of the failure. 

## Environment details
- Cloud-init version: v. 23.3.1
- Operating System Distribution: SUSE Linux Enterprise Server 15 SP4

## cloud-init logs

We are having the following error during installation and setup of cloud-init:
```
Finished processing dependencies for cloud-init==23.3+80.g0cf010e6
 Cloud-init v. 23.3.1 running 'init-local' at Thu, 12 Oct 2023 06:25:28 +0000. Up 601755.92 seconds.
  - util.py[WARNING]: failed stage init-local
 failed run of stage init-local
 ------------------------------------------------------------
 Traceback (most recent call last):
 File "/usr/lib/python3.6/site-packages/cloud_init-23.3+80.g0cf010e6-py3.6.egg/cloudinit/cmd/main.py", line 772, in status_wrapper
 ret = functor(name, args)
 File "/usr/lib/python3.6/site-packages/cloud_init-23.3+80.g0cf010e6-py3.6.egg/cloudinit/cmd/main.py", line 386, in main_init
 init.fetch(existing=existing)
 File "/usr/lib/python3.6/site-packages/cloud_init-23.3+80.g0cf010e6-py3.6.egg/cloudinit/stages.py", line 469, in fetch
 return self._get_data_source(existing=existing)
 File "/usr/lib/python3.6/site-packages/cloud_init-23.3+80.g0cf010e6-py3.6.egg/cloudinit/stages.py", line 362, in _get_data_source
 self.distro,
 File "/usr/lib/python3.6/site-packages/cloud_init-23.3+80.g0cf010e6-py3.6.egg/cloudinit/stages.py", line 155, in distro
 distro_cls = distros.fetch(distro_name)
 File "/usr/lib/python3.6/site-packages/cloud_init-23.3+80.g0cf010e6-py3.6.egg/cloudinit/distros/__init__.py", line 1413, in fetch
     % (name, looked_locs)
 ImportError: No distribution found for distro suse (searched ['suse', 'cloudinit.distros.suse'])
```

There were few similar warnings in the log which doesn't fail the process. Adding them here for clarification: 
```
copying tools/cloud-init-per -> build/scripts-3.6
| /usr/lib/python3.6/site-packages/setuptools/dist.py:476: UserWarning: Normalizing '23.3+79-g928b7e37' to '23.3+79.g928b7e37'
|   normalized_version,
| Failed loading yaml blob. Invalid format at line 33 column 1: "expected '<document start>', but found '<block mapping start>'
|   in "<unicode string>", line 33, column 1:
|     : ${cloudinit_enable="NO"}
|     ^"
| Failed loading yaml blob. Invalid format at line 31 column 1: "expected '<document start>', but found '<block mapping start>'
|   in "<unicode string>", line 31, column 1:
|     : ${cloudinit_enable="NO"}
|     ^"
| Failed loading yaml blob. Invalid format at line 31 column 1: "expected '<document start>', but found '<block mapping start>'
|   in "<unicode string>", line 31, column 1:
|     : ${cloudinit_enable="NO"}
|     ^"
| Failed loading yaml blob. Invalid format at line 19 column 1: "while scanning for the next token
| found character '\t' that cannot start any token
|   in "<unicode string>", line 19, column 1:
|     	echo -n "${command} starting"
|     ^"
| Failed loading yaml blob. Invalid format at line 31 column 1: "expected '<document start>', but found '<block mapping start>'
|   in "<unicode string>", line 31, column 1:
|     : ${cloudinit_enable="NO"}
|     ^"
| Failed loading yaml blob. Yaml load allows (<class 'dict'>,) root types, but got str instead
| Failed loading yaml blob. Yaml load allows (<class 'dict'>,) root types, but got str instead
```

**Comment by Rozzii** [comment]
HI, I would be also interested in this, I have also seen this issue.

**Comment by holmanb** [comment]
> I was trying to install cloud-init from source

Why? See the [tutorial](https://cloudinit.readthedocs.io/en/latest/tutorial/qemu.html) for getting started with using cloud-init.

> sudo cloud-init init --local 

Why did you run this? This is not how cloud-init is intended to be used. Again, check the tutorial.

**Comment by smoshiur1237** [comment]
The reason behind this issue is, suse may not have support for cloud-init in future and we don't want to depend on suse based package of cloud-init. That is why we wanted to build the cloud-init from source in suse distro. This issue points to a possible bug that `suse `disrto option is missing in the source code. Here is  the link of the folder and file where the option of suse distro is missing. 
https://github.com/canonical/cloud-init/tree/main/cloudinit/distros (missing `suse.py`)
https://github.com/canonical/cloud-init/blob/9a401b4a21ea179452143ef8c97f261c1655c539/cloudinit/distros/__init__.py#L89

**Comment by Rozzii** [comment]
Hi I would like to approach this topic from a different direction and try to explain where our confusion is coming from.
So first of all I understand that now we are talking about an enterprise distro and I can completely understand if after my explanation you wouldn't like to do anything with the issue.

We are in a situation where we have to install from source.
Thanks for your response @holmanb !

The confusion is coming from the fact that in the source code of cloud-init in the "suse" distro family there are many older SLES distro names but the current ones are missing
in case of SLES 15 SP4 and SP5 distros cloud-init detects the "variant" as "suse" and not "sles" or something similar.

So what I have expected to see is a "suse" variant name in https://github.com/canonical/cloud-init/blob/9a401b4a21ea179452143ef8c97f261c1655c539/cloudinit/distros/__init__.py#L89
and a "module" like https://github.com/canonical/cloud-init/blob/9a401b4a21ea179452143ef8c97f261c1655c539/cloudinit/distros/sles.py just with the name "suse" that would also
reference the "opensuse" module.

I understand if you say that you have an agreement with SUSE or any decision otherwise that you are not supporting newer SLES versions anymore and we should exclusively rely on the
SLES package's and their patches, but in any case I would like to clarify the situation and why this seemed to us like a bug.

**Comment by holmanb** [comment]
> suse may not have support for cloud-init in future and we don't want to depend on suse based package of cloud-init

@smoshiur1237 That is news to me, please share more. What is your source of this information? @rjschwei thoughts?

> So first of all I understand that now we are talking about an enterprise distro and I can completely understand if after my explanation you wouldn't like to do anything with the issue.

Not at all, as an open source project, we're happy to take user bug reports and contributions. The glib response was due to this looking a lot like a misguided user trying to get started the wrong way.

> I understand if you say that you have an agreement with SUSE or any decision otherwise that you are not supporting newer SLES versions anymore and we should exclusively rely on the SLES packages and their patches

Nope. If a user community wants to support an open source distro in a way that aligns with this project, we'll try to make it work as we find the time.

> We are in a situation where we have to install from source.

Details explaining why would be appreciated. I don't know of anybody that does this without distro packaging, so your use case is intriguing.

I'd  really like to get answers to my questions above, but in the meantime your requested change seems trivial. Let me know [if this branch](https://github.com/holmanb/cloud-init/tree/holmanb/why-so-many-suse) resolves the issue for you.

**Comment by Rozzii** [comment]
> > suse may not have support for cloud-init in future and we don't want to depend on suse based package of cloud-init
> 
> @smoshiur1237 That is news to me, please share more. What is your source of this information? @rjschwei thoughts?
> 
> > So first of all I understand that now we are talking about an enterprise distro and I can completely understand if after my explanation you wouldn't like to do anything with the issue.
> 
> Not at all, as an open source project, we're happy to take user bug reports and contributions. The glib response was due to this looking a lot like a misguided user trying to get started the wrong way.
> 
> > I understand if you say that you have an agreement with SUSE or any decision otherwise that you are not supporting newer SLES versions anymore and we should exclusively rely on the SLES packages and their patches
> 
> Nope. If a user community wants to support an open source distro in a way that aligns with this project, we'll try to make it work as we find the time.
> 
> > We are in a situation where we have to install from source.
> 
> Details explaining why would be appreciated. I don't know of anybody that does this without distro packaging, so your use case is intriguing.
> 
> I'd really like to get answers to my questions above, but in the meantime your requested change seems trivial. Let me know [if this branch](https://github.com/holmanb/cloud-init/tree/holmanb/why-so-many-suse) resolves the issue for you @Rozzii and @smoshiur1237, and we can try to get this sorted.

Thanks for the help!

We will test it and get back to you ASAP.

**Comment by rjschwei** [comment]
Well, lets just say that people say a lot of stuff.

Anyway, the fact is that not all patches that are carried by the distribution package are upstream. As such installing from source from GitHub will have some brokenness on SUSE (SLE and openSUSE) distributions. Thanks to @holmanb for #4421 we are getting a lot closer to having the upstream code "just work".

As far as https://github.com/canonical/cloud-init/compare/main...holmanb:cloud-init:holmanb/why-so-many-suse_ is concerned there is no SUSE distro that identifies itself as _suse_ all distro builds are already setup. As such I would think this is maybe some derivative build.

**Comment by holmanb** [comment]
@Rozzii @rjschwei @smoshiur1237 please review https://github.com/canonical/cloud-init/pull/4557
