### ISSUE TITLE
cloud-init 23.4.3 "Error: Cloud config schema errors: network: Additional properties are not allowed ('network' was unexpected)"

### ISSUE THREAD

**Issue by lsh-0** [canonical/cloud-init#4944]
# Bug report

An upgrade to `cloud-init` from `23.3.3-0ubuntu0~20.04.1` to `23.4.3-0ubuntu0~20.04.1` now produces the following validation error:

```bash
$ cloud-init --version
/usr/bin/cloud-init 23.4.3-0ubuntu0~20.04.1

$ cat /etc/cloud/cloud.cfg.d/10_enable-dhcp-ipv6.cfg 
#cloud-config
network:
  version: 2
  ethernets:
     ens5:
        dhcp4: true
        dhcp6: true

$ cloud-init schema -c /etc/cloud/cloud.cfg.d/10_enable-dhcp-ipv6.cfg
Invalid UNKNOWN_CONFIG_HEADER /etc/cloud/cloud.cfg.d/10_enable-dhcp-ipv6.cfg
Error: Cloud config schema errors: network: Additional properties are not allowed ('network' was unexpected)

Error: Invalid schema: UNKNOWN_CONFIG_HEADER
```

However, the `network` section seems to be valid v2 configuration:
https://cloudinit.readthedocs.io/en/latest/reference/network-config-format-v2.html

## Steps to reproduce the problem

See above.

## Environment details
- Cloud-init version: `23.4.3-0ubuntu0~20.04.1`
- Operating System Distribution: Ubuntu 20.04
- Cloud provider, platform or installer type: Vagrant, AWS EC2

## cloud-init logs

[cloud-init.tar.gz](https://github.com/canonical/cloud-init/files/14381645/cloud-init.tar.gz)

**Comment by blackboxsw** [comment]
Thank you for the bug report and making cloud-init better.


Some minor notes on this bug:
1. I see no warnings or errors in your cloud-init log. So, I'm presuming this concern is a post-processing step you are performing to validate configuration provided files to cloud-init to make sure schema looks good?
2. Can you please confirm that `sudo cloud-init schema --system` does not error in your environment as the `--system` parameter will check user-data and network-config against the appropriate schemas.
3. The network config YAML you provided isn't cloud-init user-data, so it really shouldn't have that declarative header (`#cloud-config`). #cloud-config is typically reserved for user-data files. It doesn't break network config processing for cloud-init because any commented lines in network config handling are ignored.line, 

Background:

What has changed in cloud-init 23.4.3 is that cloud-init user-data schema validation has gotten more strict to attempt to alert consumers of invalid config keys in #cloud-config user-data files that were previously ignored by more permissive schema validation that would just ignore unknown keys. Your file is actually a network-config file and not a #cloud-config user-data file, so the default  `--schema-type cloud-config` that is being performed is correct in raising that error. The network key is not strictly allowed in user-data files, but it is permitted in network-config files.

The subcommand `sudo cloud-init schema --system` is an alternative which can automatically differentiate between user-data and network-config provided to a system and alert to any schema errors present in the launched instance.

Note that `/etc/cloud/cloud.cfg.d` can contain more than just `#cloud-config` user-data files or parts. It aggregates [base config](https://cloudinit.readthedocs.io/en/latest/reference/base_config_reference.html) which can potentially include network config (in your case) or other base configuration keys and values beyond just strict #cloud-config user-data keys.

When using the `cloud-init schema -c YOUR_FILE` for validation, the command makes the default assumption that the file it is looking at is `--schema-type cloud-config` to represent known user-data schema. Since the file you are processing is actually network config, you'll need to provide the parameter `--schema-type network-config` to get appropriate network schema validation for this network config  file. 

That said, the only strict network config schema validation performed in 23.4.3 is for network config version: 1, So running `sudo cloud-init schema -c /etc/cloud/cloud.cfg.d/10_enable-dhcp-ipv6.cfg  --schema-type network-config` against your network version: 2 schema will only tell you: 
`Skipping network-config schema validation. No network schema for version: 2`

In cloud-init v. 24.1, (already present in Ubuntu Noble), any system with netplan installed has the ability to validate network `version: 2` schema by using `sudo cloud-init schema -c <your_file> --schema-type network-config`.

This 24.1 release of cloud-init  will also be provided as a stable upstream release back into Ubuntu Focal, Jammy and Mantic and should make it within the next couple of weeks.

**Comment by giacomo-alzetta-aiven** [comment]
@blackboxsw Hi there: could you clarify exactly what you mean by:

> What has changed in cloud-init 23.4.3 is that cloud-init user-data schema validation has gotten more strict to attempt to alert consumers of invalid config keys in #cloud-config user-data files that were previously ignored by more permissive schema validation that would just ignore unknown keys. 

In my case I have inherited some code which puts `network` config options inside user-data (together with other user-data configurations so I can't simply remove the `#cloud-config` header) and when trying to upgrade cloud-init I see this warning. My question is:

1. Has cloud-init always ignored the `network` section provided and is simply now warning about it?
2. Or is cloud-init complaining but still applying the configuration?

Since everything seem to have worked up to this point I'm wondering if in reality I can just delete that section (assuming it was always ignored in user-data and thus no-op) or if we should somehow move it in an other place.

**Comment by TheRealFalcon** [comment]
> Has cloud-init always ignored the network section provided and is simply now warning about it?

Yes, `network` is not used by cloud-config. You should be able to delete that section assuming it's only being consumed as user data.
