### ISSUE TITLE
[enhancement]: introduce a new config option to decide recoverable error status value

### ISSUE THREAD

**Issue by ani-sinha** [canonical/cloud-init#5044]
# Enhancement
cloud-init version 23.4 changes the previous status value of 0 for recoverable errors (warnings) to a new value 2. This breaks backward compatibility and existing customer and end-users might see breakage in their software stack or test routines due to this. Cannonical has decided to revert this downstream for Ubuntu releases. See https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/2048522 . We at Red Hat have made a similar decision for centos 9 stream for the same reasons. 
We propose that a new config option be introduced that users can set in order to retain backward compatibility. We can turn this ON for current RHEL releases like RHEL 9 thus retaining backward compatible value of 0 but for new release trains like RHEL 10 this can be off - hence defaulting to the new value of 2. 
I looked into the config schema but I am not sure where we should put this. Most of the config options are tied to a cc_* module. If the proposal seems reasonable and the maintainers are able to give some guidance, I may try sending a patch to this end.

**Comment by TheRealFalcon** [comment]
@ani-sinha , I understand the concern, but we want to keep the higher visibility of warnings. Without such a mechanism, warnings may go unnoticed for years while causing unexpected behavior. This is a problem that we've seen many times in the past. Sometimes breaking changes are needed in new versions to improve quality, even if it requires some rework from consumers across version boundaries. We created a [page on our docs](https://cloudinit.readthedocs.io/en/latest/explanation/return_codes.html) to give some context and guidance for how to address any new warnings and status code changes.

Downstream, we think a distro patch for existing releases is preferable to a config option, because if we were to introduce a config option, we're really just working around a problem that has a straightforward solution. We don't want an option that people would copy from examples to make problems go away without really understanding why. Also, once we get to the point where current releases go EOL, we'd want to remove such a config option, but taking the option away brings us to the same place of people being unhappy we changed something. [It's a 2-line patch](https://github.com/canonical/cloud-init/blob/ubuntu/jammy/debian/patches/status-retain-recoverable-error-exit-code.patch), so it shouldn't be too much of a burden to carry across existing releases.

**Comment by ani-sinha** [comment]
Sounds good to me. I have already applied a fix in c9s here: https://gitlab.com/redhat/centos-stream/src/cloud-init/-/commit/424eb97cff0bd97967c82214308693481f17a50a
Maybe it is simply better to drop this patch when we are ready to introduce new behaviour.
