### ISSUE TITLE
ubuntu/focal/24.2: Patch out ConditionEnvironment key in systemd/cloud-init-hotplugd.{service,socket}

### ISSUE THREAD

**Issue by aciba90** [canonical/cloud-init#5402]
Patch out the `ConditionEnvironment` keys introduced in https://github.com/canonical/cloud-init/commit/57c022d652abf53854546af5abcfffdef7fa3c6f for focal as `systemd<246` issues warnings about that unknown key.

Probably place it within the patch introduce it in: https://github.com/canonical/cloud-init/pull/5312

To do this, we need to perform a new upstream snapshot in focal to include the tip of main there.

**Comment by blackboxsw** [comment]
@aciba90 since upstream release of 24.2 will be cut and our SRU will pull from [upstream/ubuntu/focal:debian/patches/drop-unsupported-systemd-condition-environment.patch]/(https://github.com/canonical/cloud-init/blob/ubuntu/focal/debian/patches/drop-unsupported-systemd-condition-environment.patch)  is there anything additional that you suggest we do here? Our typical SRU process will be to cut/tag a upstream/24.2 tag from current tip of main. Then any SRU's to stable Ubuntu releases will be pulled from upstream/ubuntu/(focal|jammy|noble|...) which contain the expected quilt patch reverting the ConditionEnvironment variable.

**Comment by aciba90** [comment]
https://github.com/canonical/cloud-init/commit/57c022d652abf53854546af5abcfffdef7fa3c6f introduced the aforementioned key in https://github.com/canonical/cloud-init/blob/main/systemd/cloud-init-hotplugd.service, this is issue is tracking that work.

**Comment by holmanb** [comment]
Fixed in release 24.2.
